/// <reference path="../pb_data/types.d.ts" />

/**
 * Collections for the Dummy Data Generator.
 *
 * The three tables the tool used to keep in `data/dummy-data.sqlite` —
 * `configs`, `datasets`, `script_templates` — one for one.
 *
 * Every rule is `null`, which in PocketBase means "superusers only": no
 * request carrying a user token, or no token at all, can read or write these
 * collections. The Bun server authenticates as the superuser from
 * PB_ADMIN_EMAIL / PB_ADMIN_PASSWORD and is the only thing that talks to them,
 * so exposing PocketBase's port on a dev machine does not hand the database to
 * whatever else can reach it.
 *
 * Ids are supplied by the app (`cfg_…`, `ds_…`, `tpl_…`) rather than
 * autogenerated, so the ids in the REST API, in exported files and in the UI
 * stay the readable, type-tagged strings they have always been. That needs the
 * system `id` field widened from PocketBase's fixed 15-character default.
 */
migrate(
  app => {
    /** App-supplied id: `<prefix>_<hex>`, still autogeneratable as a fallback. */
    const idField = {
      type: "text",
      name: "id",
      system: true,
      primaryKey: true,
      required: true,
      min: 3,
      max: 40,
      pattern: "^[a-z0-9_]+$",
      autogeneratePattern: "[a-z0-9]{15}",
    };

    const created = { type: "autodate", name: "created", onCreate: true, onUpdate: false };
    const updated = { type: "autodate", name: "updated", onCreate: true, onUpdate: true };

    // Superusers only. PocketBase treats a null rule as "no API access".
    const lockedDown = {
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
    };

    /** Saved schemas. `schema` holds the Field[] the editor round-trips. */
    const configs = new Collection({
      name: "configs",
      type: "base",
      ...lockedDown,
      fields: [
        idField,
        { type: "text", name: "name", required: true, min: 1, max: 200 },
        { type: "text", name: "description", required: false, max: 2000 },
        // 2 MB is far more than a field list needs, and still bounded — a
        // static enum can carry a few thousand choices.
        { type: "json", name: "schema", required: true, maxSize: 2097152 },
        { type: "number", name: "rowCount", required: false, min: 1, max: 100000 },
        { type: "text", name: "seed", required: false, max: 200 },
        created,
        updated,
      ],
      indexes: ["CREATE INDEX `idx_configs_updated` ON `configs` (`updated`)"],
    });
    app.save(configs);

    /** Generated rows. One record per generation, rows stored whole as JSON. */
    const datasets = new Collection({
      name: "datasets",
      type: "base",
      ...lockedDown,
      fields: [
        idField,
        {
          type: "relation",
          name: "config",
          required: false,
          maxSelect: 1,
          collectionId: configs.id,
          // Deleting a configuration clears the reference instead of deleting
          // the data generated from it — the old ON DELETE SET NULL.
          cascadeDelete: false,
        },
        { type: "text", name: "name", required: true, min: 1, max: 200 },
        { type: "number", name: "rowCount", required: false, min: 0 },
        { type: "number", name: "fieldCount", required: false, min: 0 },
        // The generator caps a run at 100k rows; 64 MB of JSON holds that with
        // room to spare. See `MAX_DATASET_BYTES` in src/server/db.ts, which
        // rejects an oversized dataset with a readable error before it is sent.
        { type: "json", name: "rows", required: true, maxSize: 67108864 },
        created,
      ],
      indexes: ["CREATE INDEX `idx_datasets_created` ON `datasets` (`created`)"],
    });
    app.save(datasets);

    /** Script templates: JS with a ${GENERATED_DATASET} placeholder. */
    const scriptTemplates = new Collection({
      name: "script_templates",
      type: "base",
      ...lockedDown,
      fields: [
        idField,
        // Matches MAX_TEMPLATE_NAME_LENGTH / MAX_TEMPLATE_BODY_LENGTH in
        // src/lib/scriptTemplate.ts, which reject first with a better message.
        { type: "text", name: "name", required: true, min: 1, max: 120 },
        { type: "text", name: "body", required: false, max: 200000 },
        created,
        updated,
      ],
      indexes: ["CREATE INDEX `idx_script_templates_updated` ON `script_templates` (`updated`)"],
    });
    app.save(scriptTemplates);
  },
  app => {
    // Datasets reference configs, so they have to go first.
    for (const name of ["script_templates", "datasets", "configs"]) {
      try {
        app.delete(app.findCollectionByNameOrId(name));
      } catch (err) {
        // Already gone — nothing to undo.
      }
    }
  },
);
